### ISSUE TITLE
Routes menu kloppen niet

### ISSUE THREAD

**Issue by brou0039** [markgoed/cm2#26]
Wanneer vanaf een competentiepagina (bijvoorbeeld '/competencies/48) op de knop 'Student Competenties' wordt geklikt, wordt doorverwezen naar '/competencies/student/1/competencies'. Deze route constructie klopt niet, en levert een foutmelding op.

Voorgestelde oplossing:
Verander de route zodat deze het eerste gedeelte '/competencies' weg laat.

**Comment by brou0039** [comment]
Vanuit '/student/1/competencies' op de knop 'Student Competenties' klikken resulteert in een verwijzing naar '/student/1/student/1/competencies', wat ook niet klopt

**Comment by brou0039** [comment]
Dit lijkt allemaal alleen te gebeuren wanneer het scherm zo smal gemaakt wordt, dat het hamburgermenu activeert

**Comment by markgoed** [comment]
SOLVED!
