### ISSUE TITLE
Beveiliging - Bereikbaarheid van pagina's via URL zonder inloggen

### ISSUE THREAD

**Issue by brou0039** [markgoed/cm2#6]
**Probleem:**
Zonder in te loggen kunnen de pagina's waarvoor ingelogd moet worden nog wel bereikt worden via de URL. Niet echt veilig. 

**Oplossing:**
Graag aanpassen zodat elke pagina waarvoor ingelogd moet worden terugverwijst naar het inlogformulier wanneer de gebruiker niet ingelogd is.

**Comment by markgoed** [comment]
SOLVED!!
